AUTHOR = 'Daniel Greenfeld'
SITEURL = 'https://pydanny.github.com'
SITENAME = 'pydanny'
TWITTER_USERNAME = 'pydanny'
GITHUB_URL = 'https://github.com/pydanny'
DISQUS_SITENAME = 'pydanny'
THEME='notmyidea'
GOOGLE_ANALYTICS='UA-18066389-2'